// <auto-generated />
using System;

namespace Higurashi.IOS.Buriko
{
    public readonly struct BurikoOperationSpecification
    {
        public BurikoOperationSpecification(short code, string name, string signature)
        {
            Code = code;
            Name = name;
            Signature = signature;
        }

        public short Code { get; }
        public string Name { get; }
        public string Signature { get; }
    }

    public static class BurikoOperationCatalog
    {
        private static readonly BurikoOperationSpecification?[] Items = Create();

        public static BurikoOperationSpecification Get(short code)
        {
            if (code < 0 || code >= Items.Length || !Items[code].HasValue)
            {
                throw new ArgumentOutOfRangeException(nameof(code), code, "Unknown Buriko operation.");
            }

            return Items[code].Value;
        }

        private static BurikoOperationSpecification?[] Create()
        {
            var result = new BurikoOperationSpecification?[256];
            result[0] = new BurikoOperationSpecification(0, "StoreValueToLocalWork", "vi");
            result[1] = new BurikoOperationSpecification(1, "LoadValueFromLocalWork", "v");
            result[2] = new BurikoOperationSpecification(2, "SetLocalFlag", "vi");
            result[3] = new BurikoOperationSpecification(3, "SetGlobalFlag", "vi");
            result[4] = new BurikoOperationSpecification(4, "GetLocalFlag", "v");
            result[5] = new BurikoOperationSpecification(5, "GetGlobalFlag", "v");
            result[6] = new BurikoOperationSpecification(6, "CallScript", "s");
            result[7] = new BurikoOperationSpecification(7, "JumpScript", "s");
            result[8] = new BurikoOperationSpecification(8, "CallSection", "s");
            result[9] = new BurikoOperationSpecification(9, "JumpSection", "s");
            result[10] = new BurikoOperationSpecification(10, "Wait", "i");
            result[11] = new BurikoOperationSpecification(11, "WaitForInput", "");
            result[12] = new BurikoOperationSpecification(12, "SetValidityOfSkipping", "b");
            result[13] = new BurikoOperationSpecification(13, "SetValidityOfSaving", "b");
            result[14] = new BurikoOperationSpecification(14, "SetValidityOfInput", "b");
            result[15] = new BurikoOperationSpecification(15, "SetValidityOfUserEffectSpeed", "b");
            result[16] = new BurikoOperationSpecification(16, "OutputLine", "ssssi");
            result[17] = new BurikoOperationSpecification(17, "OutputLineAll", "ssi");
            result[18] = new BurikoOperationSpecification(18, "ClearMessage", "");
            result[19] = new BurikoOperationSpecification(19, "SetFontOfMessage", "iii");
            result[20] = new BurikoOperationSpecification(20, "SetSpeedOfMessage", "bi");
            result[21] = new BurikoOperationSpecification(21, "DisableWindow", "");
            result[22] = new BurikoOperationSpecification(22, "SpringText", "ii");
            result[23] = new BurikoOperationSpecification(23, "SetStyleOfMessageSwinging", "i");
            result[24] = new BurikoOperationSpecification(24, "Select", "iv");
            result[25] = new BurikoOperationSpecification(25, "PlayBGM", "isii");
            result[26] = new BurikoOperationSpecification(26, "StopBGM", "i");
            result[27] = new BurikoOperationSpecification(27, "ChangeVolumeOfBGM", "iii");
            result[28] = new BurikoOperationSpecification(28, "FadeOutBGM", "iib");
            result[29] = new BurikoOperationSpecification(29, "FadeOutMultiBGM", "iiib");
            result[30] = new BurikoOperationSpecification(30, "PlaySE", "isii");
            result[31] = new BurikoOperationSpecification(31, "StopSE", "i");
            result[32] = new BurikoOperationSpecification(32, "FadeOutSE", "ii");
            result[33] = new BurikoOperationSpecification(33, "WaitToFinishSEPlaying", "i");
            result[34] = new BurikoOperationSpecification(34, "PlayVoice", "isi");
            result[35] = new BurikoOperationSpecification(35, "WaitToFinishVoicePlaying", "i");
            result[36] = new BurikoOperationSpecification(36, "PreloadBitmap", "s");
            result[37] = new BurikoOperationSpecification(37, "StartShakingOfAllObjects", "iiiiib");
            result[38] = new BurikoOperationSpecification(38, "TerminateShakingOfAllObjects", "ib");
            result[39] = new BurikoOperationSpecification(39, "StartShakingOfWindow", "iiiiib");
            result[40] = new BurikoOperationSpecification(40, "TerminateShakingOfWindow", "ib");
            result[41] = new BurikoOperationSpecification(41, "StartShakingOfBustshot", "iiiiiib");
            result[42] = new BurikoOperationSpecification(42, "TerminateShakingOfBustshot", "iib");
            result[43] = new BurikoOperationSpecification(43, "StartShakingOfSprite", "iiiiiib");
            result[44] = new BurikoOperationSpecification(44, "TerminateShakingOfSprite", "iib");
            result[45] = new BurikoOperationSpecification(45, "ShakeScreen", "iiiii");
            result[46] = new BurikoOperationSpecification(46, "ShakeScreenSx", "ii");
            result[47] = new BurikoOperationSpecification(47, "DrawBG", "sib");
            result[48] = new BurikoOperationSpecification(48, "FadeBG", "ib");
            result[49] = new BurikoOperationSpecification(49, "DrawBGWithMask", "ssiib");
            result[50] = new BurikoOperationSpecification(50, "DrawScene", "si");
            result[51] = new BurikoOperationSpecification(51, "DrawSceneWithMask", "ssiii");
            result[52] = new BurikoOperationSpecification(52, "ChangeScene", "sii");
            result[53] = new BurikoOperationSpecification(53, "FadeScene", "i");
            result[54] = new BurikoOperationSpecification(54, "FadeSceneWithMask", "siii");
            result[55] = new BurikoOperationSpecification(55, "DrawBustshot", "isiiibiiiiiiiiib");
            result[56] = new BurikoOperationSpecification(56, "MoveBustshot", "isiiiiib");
            result[57] = new BurikoOperationSpecification(57, "FadeBustshot", "ibiiiiib");
            result[58] = new BurikoOperationSpecification(58, "DrawBustshotWithFiltering", "issiiibiiiiiiib");
            result[59] = new BurikoOperationSpecification(59, "DrawFace", "sib");
            result[60] = new BurikoOperationSpecification(60, "FadeFace", "ib");
            result[61] = new BurikoOperationSpecification(61, "ExecutePlannedControl", "b");
            result[62] = new BurikoOperationSpecification(62, "DrawSprite", "issiiiiiibbiiiib");
            result[63] = new BurikoOperationSpecification(63, "DrawSpriteWithFiltering", "issiiibbiiiib");
            result[64] = new BurikoOperationSpecification(64, "FadeSprite", "iib");
            result[65] = new BurikoOperationSpecification(65, "FadeSpriteWithFiltering", "isiib");
            result[66] = new BurikoOperationSpecification(66, "MoveSprite", "iiiiiiiiib");
            result[67] = new BurikoOperationSpecification(67, "MoveSpriteEx", "isiiviiiiib");
            result[68] = new BurikoOperationSpecification(68, "ControlMotionOfSprite", "iivi");
            result[69] = new BurikoOperationSpecification(69, "GetPositionOfSprite", "vi");
            result[70] = new BurikoOperationSpecification(70, "EnableHorizontalGradation", "iib");
            result[71] = new BurikoOperationSpecification(71, "DisableGradation", "ib");
            result[72] = new BurikoOperationSpecification(72, "EnlargeScreen", "iiiibib");
            result[73] = new BurikoOperationSpecification(73, "DisableEffector", "ib");
            result[74] = new BurikoOperationSpecification(74, "EnableBlur", "iib");
            result[75] = new BurikoOperationSpecification(75, "DisableBlur", "ib");
            result[76] = new BurikoOperationSpecification(76, "DrawFilm", "iiiiiiib");
            result[77] = new BurikoOperationSpecification(77, "FadeFilm", "ib");
            result[78] = new BurikoOperationSpecification(78, "SetValidityOfFilmToFace", "b");
            result[79] = new BurikoOperationSpecification(79, "FadeAllBustshots", "ib");
            result[80] = new BurikoOperationSpecification(80, "FadeBustshotWithFiltering", "isibiiib");
            result[81] = new BurikoOperationSpecification(81, "SetDrawingPointOfMessage", "ii");
            result[82] = new BurikoOperationSpecification(82, "Negative", "ib");
            result[83] = new BurikoOperationSpecification(83, "EnableJumpingOfReturnIcon", "");
            result[84] = new BurikoOperationSpecification(84, "SetValidityOfWindowDisablingWhenGraphicsControl", "b");
            result[85] = new BurikoOperationSpecification(85, "SetValidityOfInterface", "b");
            result[86] = new BurikoOperationSpecification(86, "ShowTips", "i");
            result[87] = new BurikoOperationSpecification(87, "ShowChapterScreen", "");
            result[88] = new BurikoOperationSpecification(88, "ShowExtras", "");
            result[89] = new BurikoOperationSpecification(89, "ShowChapterPreview", "");
            result[90] = new BurikoOperationSpecification(90, "SavePoint", "ss");
            result[91] = new BurikoOperationSpecification(91, "PlaceViewTip", "i");
            result[92] = new BurikoOperationSpecification(92, "PlaceViewTip2", "ii");
            result[93] = new BurikoOperationSpecification(93, "DrawStandgraphic", "isbiib");
            result[94] = new BurikoOperationSpecification(94, "DrawBustFace", "isbi");
            result[95] = new BurikoOperationSpecification(95, "PlusStandgraphic1", "is");
            result[96] = new BurikoOperationSpecification(96, "PlusStandgraphic2", "is");
            result[97] = new BurikoOperationSpecification(97, "PlusStandgraphic3", "is");
            result[98] = new BurikoOperationSpecification(98, "FadeAllBustshots2", "ib");
            result[99] = new BurikoOperationSpecification(99, "FadeAllBustshots3", "ib");
            result[100] = new BurikoOperationSpecification(100, "BlurOffOn", "ii");
            result[101] = new BurikoOperationSpecification(101, "TitleScreen", "");
            result[102] = new BurikoOperationSpecification(102, "OpenGallery", "");
            result[103] = new BurikoOperationSpecification(103, "HideGallery", "");
            result[104] = new BurikoOperationSpecification(104, "RevealGallery", "");
            result[105] = new BurikoOperationSpecification(105, "CloseGallery", "");
            result[106] = new BurikoOperationSpecification(106, "SetSkipAll", "b");
            result[107] = new BurikoOperationSpecification(107, "SetValidityOfTextFade", "b");
            result[108] = new BurikoOperationSpecification(108, "Break", "");
            result[109] = new BurikoOperationSpecification(109, "LanguagePrompt", "");
            result[110] = new BurikoOperationSpecification(110, "GetAchievement", "s");
            result[111] = new BurikoOperationSpecification(111, "CheckTipsAchievements", "");
            result[112] = new BurikoOperationSpecification(112, "SetFontId", "i");
            result[113] = new BurikoOperationSpecification(113, "SetCharSpacing", "i");
            result[114] = new BurikoOperationSpecification(114, "SetLineSpacing", "i");
            result[115] = new BurikoOperationSpecification(115, "SetFontSize", "i");
            result[116] = new BurikoOperationSpecification(116, "SetWindowPos", "ii");
            result[117] = new BurikoOperationSpecification(117, "SetWindowSize", "ii");
            result[118] = new BurikoOperationSpecification(118, "SetWindowMargins", "iiii");
            result[119] = new BurikoOperationSpecification(119, "SetNameFormat", "s");
            result[120] = new BurikoOperationSpecification(120, "SetScreenAspect", "s");
            result[121] = new BurikoOperationSpecification(121, "SetGUIPosition", "ii");
            result[122] = new BurikoOperationSpecification(122, "ModEnableNVLModeInADVMode", "");
            result[123] = new BurikoOperationSpecification(123, "ModDisableNVLModeInADVMode", "");
            result[124] = new BurikoOperationSpecification(124, "ModADVModeSettingLoad", "siiiiiiiiiiii");
            result[125] = new BurikoOperationSpecification(125, "ModNVLModeSettingLoad", "siiiiiiiiiiii");
            result[126] = new BurikoOperationSpecification(126, "ModNVLADVModeSettingLoad", "siiiiiiiiiiii");
            result[127] = new BurikoOperationSpecification(127, "ModCallScriptSection", "ss");
            result[128] = new BurikoOperationSpecification(128, "ModDrawCharacter", "iissiiibiiiiiiiiib");
            result[129] = new BurikoOperationSpecification(129, "ModDrawCharacterWithFiltering", "iisssiiibiiiiiiib");
            result[130] = new BurikoOperationSpecification(130, "ModPlayVoiceLS", "iisib");
            result[131] = new BurikoOperationSpecification(131, "ModPlayMovie", "s");
            result[132] = new BurikoOperationSpecification(132, "ModSetConfigFontSize", "i");
            result[133] = new BurikoOperationSpecification(133, "ModSetChapterJumpFontSize", "ii");
            result[134] = new BurikoOperationSpecification(134, "ModSetHighestChapterFlag", "ii");
            result[135] = new BurikoOperationSpecification(135, "ModGetHighestChapterFlag", "i");
            result[136] = new BurikoOperationSpecification(136, "ModSetMainFontOutlineWidth", "i");
            result[137] = new BurikoOperationSpecification(137, "ModSetLayerFilter", "iis");
            result[138] = new BurikoOperationSpecification(138, "ModAddArtset", "sss");
            result[139] = new BurikoOperationSpecification(139, "ModClearArtsets", "");
            result[140] = new BurikoOperationSpecification(140, "ModRyukishiModeSettingLoad", "siiiiiiiiiiii");
            result[141] = new BurikoOperationSpecification(141, "ModRyukishiSetGuiPosition", "ii");
            result[142] = new BurikoOperationSpecification(142, "ModPlayBGM", "isiii");
            result[143] = new BurikoOperationSpecification(143, "ModFadeOutBGM", "iibi");
            result[144] = new BurikoOperationSpecification(144, "ModAddBGMset", "sss");
            result[145] = new BurikoOperationSpecification(145, "ModAddSEset", "sss");
            result[146] = new BurikoOperationSpecification(146, "ModAddAudioset", "ssssiiii");
            result[147] = new BurikoOperationSpecification(147, "ModGenericCall", "ss");
            return result;
        }
    }
}
